"""user relations update

Revision ID: c4cf728b2c5d
Revises: 113b010712d7
Create Date: 2025-07-31 11:50:11.776463

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "c4cf728b2c5d"
down_revision: Union[str, Sequence[str], None] = "113b010712d7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("user_household_id_fkey"), "user", type_="foreignkey")
    op.create_foreign_key(
        None, "user", "household", ["household_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="foreignkey")
    op.create_foreign_key(
        op.f("user_household_id_fkey"), "user", "household", ["household_id"], ["id"]
    )
    # ### end Alembic commands ###
